# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=250)),
                ('ssn', models.IntegerField()),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('telephone', models.IntegerField()),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
            ],
        ),
    ]
