# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_instructor'),
        ('Class', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='instructor',
        ),
        migrations.AddField(
            model_name='class',
            name='instructor',
            field=models.ManyToManyField(to='business.Instructor'),
        ),
    ]
