# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0002_auto_20171215_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='allocated_room_variable',
            field=models.CharField(default='Room', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='class_location_variable',
            field=models.CharField(default='Location', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='class_name_variable',
            field=models.CharField(default='Class', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='description_variable',
            field=models.CharField(default='Description', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='instructor_variable',
            field=models.CharField(default='Instructor', max_length=100),
            preserve_default=False,
        ),
    ]
