# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0003_auto_20171221_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='end_date_variable',
            field=models.CharField(default='End Date', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='start_date_variable',
            field=models.CharField(default='Start Date', max_length=100),
            preserve_default=False,
        ),
    ]
